Home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('about', views.about.as_view(), name='about'),
    path('floor/<slug:slug>/', views.concrete_floors.as_view(), name='concrete_floors'),
    path('polymer-floors', views.polymer.as_view(), name='polymer'),
    path('contacts', views.contacts.as_view(), name='contacts'),
    path('vacancies', views.vacancies.as_view(), name='vacancies'),
    path('vacancy/<slug:slug>', views.vacancy.as_view(), name='vacancy'),
    path('solutions', views.ready_solutions.as_view(), name='ready_solutions'),
    path('solution/<slug:slug>', views.ready_solution.as_view(), name='ready_solution'),
    path('objects', views.ready_objects.as_view(), name='ready_objects'),
    path('object/<slug:slug>', views.ready_object.as_view(), name='ready_object'),
    path('add_application', views.AdviseFreeView.as_view(), name='application'),
    path('add_resume', views.ResumeFreeView.as_view(), name='add_resume'),
    path('add_order', views.OrderPaymentView.as_view(), name='add_order'),
    path('add_order_object', views.OrderPaymentObjectView.as_view(), name='add_order_object')

]

djangofloors/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    import mimetypes
    mimetypes.add_type("application/javascript", ".js", True)

Home/models.py
from django.db import models
from django.urls import reverse


# Услуги
class Services(models.Model):
    name = models.CharField(verbose_name='Наименование Услуги', max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    price = models.IntegerField(verbose_name='Цена')
    osv_image = models.ImageField(verbose_name='Фотография главная', upload_to='images/osv/')
    # CEO
    seo_keywords = models.TextField(verbose_name='Слова поиска', help_text='Полы;Полы по 400 руб;')
    seo_description = models.TextField(verbose_name='Описание сео', help_text='')
    # Основание
    description_os = models.TextField(verbose_name='Описание Основания')
    images_os = models.ImageField(verbose_name='Фото Основания', upload_to='images/base/')
    # slider_os
    # Блок два
    images_two = models.ImageField(verbose_name='Фото Основания', upload_to='images/two/')
    title = models.CharField(max_length=200, verbose_name='Название второго блока')
    description_two = models.TextField(verbose_name='Описание второго блока')
    # Блок три
    images_three = models.ImageField(verbose_name='Фото Основания', upload_to='images/three/')
    title_three = models.CharField(max_length=200, verbose_name='Название третьего блока')
    description_three_1 = models.TextField(verbose_name='Описание_1 третьего блока')
    description_three_2 = models.TextField(verbose_name='Описание_2 третьего блока')
    description_three_3 = models.TextField(verbose_name='Описание_3 третьего блока')
    # Блок четыре
    title_four = models.CharField(max_length=200, verbose_name='Название четвертого блока')
    description_four_1 = models.TextField(verbose_name='Описание_1 четвертого блока')
    description_four_2 = models.TextField(verbose_name='Описание_2 четвертого блока')
    description_four_3 = models.TextField(verbose_name='Описание_3 четвертого блока')
    # slider_four
    # Требования
    demand = models.CharField(max_length=100, verbose_name='Описание требования')

    # demands
    # Преимущества
    # Advantages
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('concrete_floors', kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"


class Slider_os(models.Model):
    service = models.ForeignKey(Services, verbose_name="Услуга", on_delete=models.CASCADE)
    img = models.ImageField(verbose_name='Фотография', upload_to='images/slider/base/')


class Slider_four(models.Model):
    service = models.ForeignKey(Services, verbose_name="Услуга", on_delete=models.CASCADE)
    img = models.ImageField(verbose_name='Фотография', upload_to='images/slider/four/')


class Demands(models.Model):
    service = models.ForeignKey(Services, verbose_name="Услуга", on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Наименование требования', max_length=50)
    description = models.CharField(verbose_name='Краткое пояснение требования', max_length=100, null=True, blank=True)


class Advantages(models.Model):
    service = models.ForeignKey(Services, verbose_name="Услуга", on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Наименование требования', max_length=50)
    img = models.ImageField(verbose_name='Фотография', upload_to='images/advantages/')


class ExampleSlider(models.Model):
    service = models.ForeignKey(Services, verbose_name="Услуга", on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Наимемование примера', max_length=50)
    img = models.ImageField(verbose_name='Фотография', upload_to='images/Example/')


# Конец Услуги
# Готовые решения
class Solutions(models.Model):
    title = models.CharField(verbose_name='Название', max_length=200)
    images_png = models.TextField(verbose_name='Фотография иконки')
    description = models.TextField(verbose_name='Краткое описание')
    slug = models.SlugField(max_length=200, unique=True)
    price = models.IntegerField(verbose_name='Цена')
    # SEO
    seo_keywords = models.TextField(verbose_name='Слова поиска', help_text='ПолыПполы по 400 руб;')
    seo_description = models.TextField(verbose_name='Описание сео', help_text='')
    # Плюсы
    images_fon = models.ImageField(verbose_name='Фотография для фона', upload_to='images/solutions/fon')
    # Pluses
    # Основание
    description_os_1 = models.TextField(verbose_name='Описание Основания')
    description_os_2 = models.TextField(verbose_name='Описание Основания')
    # SliderSolutionsOs
    # Блок два
    images_two = models.ImageField(verbose_name='Фото Блок два', upload_to='images/solutions/two/')
    title_two = models.CharField(max_length=200, verbose_name='Название второго блока')
    description_two_1 = models.TextField(verbose_name='Описание второго блока 1')
    description_two_2 = models.TextField(verbose_name='Описание второго блока 2')
    # Блок три
    title_three = models.CharField(max_length=200, verbose_name='Название третьего блока')
    description_three_1 = models.TextField(verbose_name='Описание_1 третьего блока')
    description_three_2 = models.TextField(verbose_name='Описание_2 третьего блока')
    description_three_3 = models.TextField(verbose_name='Описание_3 третьего блока')
    # Блок четыре
    title_four = models.CharField(max_length=200, verbose_name='Название четвертого блока')
    subtitle = models.CharField(max_length=200, verbose_name='Подзаголовок  третьего блока')
    images_four_1 = models.ImageField(verbose_name='Фото Блок четыре 1', upload_to='images/solutions/four/one/')
    # DemandsSolutionOne
    images_four_2 = models.ImageField(verbose_name='Фото Блок четыре 2', upload_to='images/solutions/four/two/')
    # DemandsSolutionTwo
    # Требования
    demand = models.CharField(max_length=100, verbose_name='Описание требования')
    # DemandsSolution
    # Конец
    description_finish = models.TextField(verbose_name='Описание в конце')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('ready_solution', kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "Готовое решение"
        verbose_name_plural = "Готовые решения"


class Pluses(models.Model):
    """Плюсы готовых решений """
    solution = models.ForeignKey(Solutions, verbose_name="Готовое решение", on_delete=models.CASCADE)
    description = models.TextField(verbose_name='Описание', max_length=100)


class SliderSolutionsOs(models.Model):
    solution = models.ForeignKey(Solutions, verbose_name="Готовое решение", on_delete=models.CASCADE)
    img = models.ImageField(verbose_name='Фотография', upload_to='images/slider/solution/base/')


class DemandsSolutionOne(models.Model):
    solution = models.ForeignKey(Solutions, verbose_name="Готовое решение", on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Действие', max_length=200)
    index = models.IntegerField(verbose_name='Индекс шага')


class DemandsSolutionTwo(models.Model):
    solution = models.ForeignKey(Solutions, verbose_name="Готовое решение", on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Действие', max_length=200)
    index = models.IntegerField(verbose_name='Индекс шаг')


class DemandsSolution(models.Model):
    solution = models.ForeignKey(Solutions, verbose_name="Готовое решение", on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Наименование требования', max_length=50)
    description = models.CharField(verbose_name='Краткое пояснение требования', max_length=100, null=True, blank=True)


# Конец

# Контакты
class Contact(models.Model):
    address = models.CharField(verbose_name='Адрес', max_length=500)
    address_map = models.CharField(verbose_name='Адрес на карте', max_length=500)
    phone = models.CharField(verbose_name='Телефон', max_length=10)
    email = models.EmailField(verbose_name='Email')
    inn = models.CharField(verbose_name='ИНН', max_length=200)
    kpp = models.CharField(verbose_name='КПП', max_length=200)
    payment = models.CharField(verbose_name='Расчетный счет', max_length=200)
    bank = models.CharField(verbose_name='Банк', max_length=200)
    ogrn = models.CharField(verbose_name='ОГРН', max_length=200)
    doc_potent = models.FileField(verbose_name='Документ о патенте', upload_to='file/doc/')
    doc_licenses = models.FileField(verbose_name='Лицензии', upload_to='file/doc/')
    doc_bank = models.FileField(verbose_name='Файл Реквезитов', upload_to='file/doc/')

    class Meta:
        verbose_name = "Кантакт"
        verbose_name_plural = "Контакты"


class Work(models.Model):
    """технология работы"""
    contact = models.ForeignKey(Contact, verbose_name="Услуга", on_delete=models.CASCADE)
    index = models.IntegerField(verbose_name='Индекс шага')
    images = models.ImageField(verbose_name='Фотография', upload_to='images/work/')
    description = models.TextField(verbose_name='Краткое описание')


class Employee(models.Model):
    """Ключевые сотрудники"""
    contact = models.ForeignKey(Contact, verbose_name='Сайт', on_delete=models.CASCADE)
    fio = models.CharField(verbose_name='ФИО сотрудника', max_length=500)
    images = models.ImageField(verbose_name='Фотография сотрудника', upload_to='images/user/')
    description = models.TextField(verbose_name='Описание')
    phone = models.CharField(verbose_name='Телефон', max_length=10)
    email = models.EmailField(verbose_name='Email')


class LegalDocumentation(models.Model):
    """ПРАВОВАЯ ДОКУМЕНТАЦИЯ"""
    contact = models.ForeignKey(Contact, verbose_name='Сайт', on_delete=models.CASCADE)
    images = models.ImageField(verbose_name='Фотография Документа', upload_to='images/doc/')
    description = models.TextField(verbose_name='Описание', max_length=500)


# Конец
# Вакансии
class Vacancy(models.Model):
    name = models.CharField(verbose_name='Наименование Вакансии', max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    price = models.IntegerField(verbose_name='Зарплата')

Home/forms.py
from django import forms
from snowpenguin.django.recaptcha3.fields import ReCaptchaField

from .models import AdviseFree, Resume, OrderPayment, OrderPaymentObject


class AdviseFreeForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = AdviseFree
        fields = ('name', 'phone', 'captcha')


class ResumeFreeForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = Resume
        fields = ('name', 'phone', 'url', 'captcha')


class OrderPaymentForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = OrderPayment
        fields = ('name', 'phone', 'service', 'captcha')


class OrderPaymentObjectForm(forms.ModelForm):
    captcha = ReCaptchaField()

    class Meta:
        model = OrderPaymentObject
        fields = ('name', 'phone', 'service', 'captcha')

Home/templates/home/concrete-floors.html
{% extends "base.html" %}
{% load my_filters %}
{% load static %}
{% block title %}{{ services.name }}{% endblock %}
{% block metategi %}
    <meta name="description" content="{{ services.seo_description }}">
    <meta name="keywords" content="{{ services.seo_keywords }}">
{% endblock %}
{% block content %}

    <div class="container">
        <div class="breadcrumbs">
            <a href="{% url 'index' %}">Главная</a>
            <span>{{ services.name }}</span>
        </div>
        <div class="d-md-flex d-block align-items-center">
            <h2 class="col-md-7 p-0">{{ services.name }} палы
                по России от {{ services.price }} руб/м<sup>2</sup></h2>
            <div class="ml-auto text-left mt-3 mt-md-0">
                <a href="#" class="button-calculation" data-toggle="modal" data-target="#orderModal">
                    Заказать расчет
                </a>
            </div>
        </div>
        <div class="mt-5 main-banner">
            <img src="{{ services.osv_image.url }}" class="img-fluid" alt="{{ services.osv_image.name }}">
        </div>
        <div class="concrete-floors-tech">
            <h2>Технология
                {{ services.name|inflect_name:'gent,sing' }} пола</h2>
            <div class="row">
                <div class="col-lg-2 col-md-5 mt-5">
                    <h3>Основание</h3>
                </div>
                <div class="col-lg-4 col-md-7 mt-5">
                    <div class="sf-content">
                        {{ services.description_os }}
                    </div>
                </div>
                <div class="col-lg-6 mt-3 mt-lg-0 text-center">
                    <img src="{{ services.images_os.url }}" class="img-fluid">
                </div>
            </div>
        </div>
        <div class="concrete-carousel-block">
            <div id="techCarousel" class="carousel-590 carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    {% for photos in services.slider_os_set.all %}
                        <div class="carousel-item">
                            <img src="{{ photos.img.url }}" class="img-fluid">
                        </div>
                    {% endfor %}
                </div>
                <div class="row mt-3">
                    <div class="col-2">
                        <a href="#techCarousel" class="arrow left" data-slide="prev">
                        </a>
                    </div>
                    <div class="col-8 carousel-nav">
                        <div class=" carousel-indicators">
                            {% for count in services.slider_os_set.count|times %}
                                <span data-target="#techCarousel" data-slide-to="{{ count }}"
                                      class="{% if forloop.first %}active{% endif %}"></span>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-2 text-right">
                        <a href="#techCarousel" class="arrow right" data-slide="next">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="reinforce" style="background-image: url('{{ services.images_two.url }}')">
        <div class="container">
            <div class="reinforce-block">
                <h3>{{ services.title }}</h3>
                <div class="sf-content">
                    {{ services.description_two }}
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="reinforce-fibra">
            <div class="row">
                <div class="col-lg-3 col-md-4">
                    <h3>{{ services.title_three }}</h3>
                </div>
                <div class="col-lg-6 col-md-8">
                    <div class="row sf-content">
                        <div class="col-md-6">
                            {{ services.description_three_1 }}
                        </div>
                        <div class="col-md-6 mt-3 mt-md-0">
                            {{ services.description_three_2 }}
                        </div>
                        <div class="red-frame mt-4">
                            {{ services.description_three_3 }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-5">
            <img src="{{ services.images_three.url }}" class="img-fluid">
        </div>
        {#  Блок четыре #}
        <div class="concreting">
            <div class="row">
                <div class="col-ld-3 col-md-4">
                    <h3>{{ services.title_four }}</h3>
                </div>
                <div class="col-lg-6 col-md-8">
                    <div class="row sf-content">
                        <div class="col-md-6">
                            {{ services.description_four_1 }}
                        </div>
                        <div class="col-md-6 mt-3 mt-md-0">
                            <div>
                                {{ services.description_four_2 }}
                            </div>
                            <div class="red-frame mt-4">
                                {{ services.description_four_3 }}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div id="concretingCarousel" class="carousel-590 carousel slide" data-ride="carousel">
            <div class="carousel-inner">
                {% for photos in services.slider_four_set.all %}
                    <div class="carousel-item">
                        <img src="{{ photos.img.url }}" class="img-fluid">
                    </div>
                {% endfor %}
            </div>
            <div class="row mt-3">
                <div class="col-2">
                    <a href="#concretingCarousel" class="arrow left" data-slide="prev">
                    </a>
                </div>
                <div class="col-8 carousel-nav">
                    <div class=" carousel-indicators">
                        {% for count in services.slider_four_set.count|times %}
                            <span data-target="#concretingCarousel" data-slide-to="{{ count }}"
                                  class="{% if forloop.first %}active{% endif %}"></span>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-2 text-right">
                    <a href="#concretingCarousel" class="arrow right" data-slide="next">
                    </a>
                </div>
            </div>
        </div>
        {# Требования #}
        <div class="advantages">
            <div class="row">
                <div class="col-md-6">
                    <div class="advantages-title mx-3">
                        {{ services.demand }}
                    </div>
                </div>
                <div class="col-md-6 mt-3 mt-md-0">
                    <ul class="advantages-list mx-3">
                        {% for demand in services.demands_set.all %}
                            <li>
                                {{ demand.name }}
                                {% if demand.description %}
                                    <div class="sf-content">{{ demand.description }}</div>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                {# Преимущества#}
                <div class="col red-frame text-center mt-3">
                    <div class="red-frame-title">
                        Преимущества {{ services.name|inflect_name:'plur,gent' }} полов
                    </div>
                    <div class="d-md-flex   justify-content-center">
                        {% for i in services.advantages_set.all %}
                            <div class="plus-item">
                                <img src="{{ i.img.url }}" class="img-fluid">
                                <div>{{ i.name }}</div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="examples-carousel">
        <div class="container">
            <h2 class="text-center">Для чего делают {{ services.name }} полы</h2>
            <div id="exampleCarousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    {% for example in services.exampleslider_set.all %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                        <img src="{{ example.img.url }}" class="img-fluid">
                        <h3 class="mt-3 pr-5 text-center">{{ example.name }}</h3>
                    </div>
                    {% endfor %}
                </div>
                <div class="example-carousel-arrow">
                    <a href="#exampleCarousel" class="arrow left" data-slide="prev">
                    </a>
                    <a href="#exampleCarousel" class="arrow right ml-4" data-slide="next">
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% include 'contact_us.html' %}
    <div class="modal fade" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Заказать расчёт</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{% url 'add_order' %}" id="form_add_order">
                    {% csrf_token %}
                    <input type="hidden" name="service" value="{{ services.pk }}">
                    <input class="form-field" type="text" placeholder="Ваше имя*" name="name">
                    <input class="form-field" type="text" placeholder="Введите номер телефона*" name="phone">
                    {{ form.captcha }}
                    <button class="order-btn">Отправить заявку</button>
                    <div class="sf-content form-small-text w-100 text-center mt-2 mx-auto">Нажимая кнопку вы соглашаетесь с правилами
                        обработки персональных данных
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Home/templates/home/solution.html
{% extends "base.html" %}
{% load my_filters %}
{% load static %}
{% block title %}{{ solutions.title }}{% endblock %}
{% block metategi %}
    <meta name="description" content="{{ solutions.seo_description }}">
    <meta name="keywords" content="{{ solutions.seo_keywords }}">
{% endblock %}
{% block content %}

    <div class="container">
        <div class="breadcrumbs">
            <a href="{% url 'index' %}">Главная</a>
            <a href="{% url 'ready_solutions' %}">Готовые решения</a>
            <span>{{ solutions.title }}</span>
        </div>
        <div class="row">
            <div class="col-md-7">
                <h2>Полы для {{ solutions.title|inflect_name:'plur,gent' }}
                    по России от {{ solutions.price }} руб/м2
                </h2>
            </div>
            <div class="col-md-5 mt-3 mt-md-0">
                <div class="row sf-content fs-16">
                    {% for plus in solutions.pluses_set.all %}
                        <div class="d-flex d-lg-block col-lg-5 mt-3 mt-md-0">
                            <div class="mr-3"><img src="{% static 'img/top-arrow.png' %}"></div>
                            <div class="mt-lg-3">{{ plus.description }}</div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="mt-5 main-banner">
            <img src="{{ solutions.images_fon.url }}" class="img-fluid">
        </div>
        <div class="about-project">
            <h2>Готовое решение пола для {{ solutions.title|inflect_name:'sing,gent' }}</h2>
            <div class="row mt-5">
                <div class="col-lg-3">
                    <h3>Описание</h3>
                </div>
                <div class="col-lg-7">
                    <div class="sf-content">
                        Основой любого пола является существующее<br> основание:
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="text-block-grey">
                                {{ solutions.description_os_1 }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="text-block-grey">
                                {{ solutions.description_os_2 }}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="about-project-carousel mt-4">
                <div id="aboutProjectCarousel" class="carousel-590 carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        {% for slider in solutions.slidersolutionsos_set.all %}
                            <div class="carousel-item {% if slider.first %}active{% endif %}">
                                <img src="{{ slider.img.url }}" class="img-fluid">
                            </div>
                        {% endfor %}
                    </div>
                    <div class="row mt-3">
                        <div class="col-2">
                            <a href="#aboutProjectCarousel" class="arrow left" data-slide="prev">
                            </a>
                        </div>
                        <div class="col-8 carousel-nav">
                            <div class="carousel-indicators">
                                {% for count in solutions.slidersolutionsos_set.count|times %}
                                    <span data-target="#aboutProjectCarousel" data-slide-to="{{ count }}"
                                          class="{% if slider.first %}active{% endif %}"></span>
                                {% endfor %}

                            </div>
                        </div>
                        <div class="col-2 text-right">
                            <a href="#aboutProjectCarousel" class="arrow right" data-slide="next">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="article-warehouse">
            <div class="row">
                <div class="col-lg-3">
                    <h3 class="line">{{ solutions.title_two }}</h3>
                </div>
                <div class="col-lg-9">
                    <div class="row sf-content">
                        <div class="col-lg-4 col-md-6">
                            {{ solutions.description_two_1 }}
                        </div>
                        <div class="col-lg-4 col-md-6">
                            {{ solutions.description_two_2 }}
                        </div>
                    </div>
                    <img src="{{ solutions.images_two.url }}" class="img-fluid mt-4">
                </div>
            </div>
        </div>
        <div class="concreting">
            <div class="row">
                <div class="col-lg-3">
                    <h3>{{ solutions.title_three }}</h3>
                </div>
                <div class="col-lg-6">
                    <div class="row sf-content">
                        <div class="col-md-6">
                            {{ solutions.description_three_1 }}
                        </div>
                        <div class="col-md-6 mt-3 mt-md-0 ">
                            <div>
                                {{ solutions.description_three_2 }}
                            </div>
                            <div class="red-frame mt-4">
                                {{ solutions.description_three_3 }}
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <div class="warehouse-space">
            <h2>{{ solutions.title_four }}</h2>
            <div class="row mt-5">
                <div class="col-lg-3 col-md-6">
                    <h3>{{ solutions.subtitle }}</h3>
                    <img src="{{ solutions.images_four_1.url }}" class="img-fluid mt-2">
                </div>
                <div class="col-lg-3 col-md-6 pt-5 line-right">
                    <ol class="sf-content">
                        {% for name in solutions.demandssolutionone_set|order_all:'index' %}
                            <li>{{ name.name }}</li>
                        {% endfor %}
                    </ol>
                </div>
                <div class="col-lg-3 col-md-6">
                    <img src="{{ solutions.images_four_2.url }}" class="img-fluid mt-5">
                </div>
                <div class="col-lg-3 col-md-6 pt-5">
                    <ol class="sf-content">
                        {% for name in solutions.demandssolutiontwo_set|order_all:'index' %}
                            <li>{{ name.name }}</li>
                        {% endfor %}
                    </ol>
                </div>
            </div>
        </div>
        <div class="advantages-warehouse mt-5">
            <div class="row">
                <div class="col-lg-3"></div>
                <div class="col-lg-7">
                    <div class="row">
                        <div class="col-md-5">
                            <div class="advantages-title">
                                {{ solutions.demand }}
                            </div>
                        </div>
                        <div class="col-md-6 mt-3 mt-md-0">
                            <ul class="advantages-list mx-3">
                                {% for dem in solutions.demandssolution_set.all %}
                                    <li>
                                    {{ dem.name }}
                                    <div class="sf-content">{{ dem.description }}</div>
                                </li>
                                {% endfor %}

                            </ul>
                        </div>
                        <div class="col sf-content mt-3">
                            {{ solutions.description_finish }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include 'contact_us.html' %}

{% endblock %}